name: 'Custom Github Action'
description: 'A Github Action that takes an input and returns the square of the number'
inputs:
  num:
    description: 'Enter a number'
    required: true
    default: "1"
  to_id:
    description: 'primary email that needs to be addressed to'
    required: true
    default: "sre_nxg_gen_ops@hm.com"
  cc_id:
    description: 'primary email that needs to be addressed to'
    required: true
    default: ""
  start_time:
    description: 'time when the run started'
    required: true
    default: ""
  content:
    description: 'content of the email'
    required: true
    default: ""
  failure:
    description: 'failure message'
    required: true
    default: ""
outputs:
  num_squared:
    description: 'Square of the input'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: End Time
      shell: bash
      id: end_time
      run: echo "END_TIME=$(date +%s%3N)" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v4
    - name: list all action files
      shell: bash
      run: ls ${{github.action_path}} * -r
    - name: list all repo files
      shell: bash
      run: ls * -r
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r ${{github.action_path}}/requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
          echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
          echo "INPUT_TO_ID=${{ inputs.to_id }}" >> $GITHUB_ENV
          echo "INPUT_CC_ID=${{ inputs.cc_id }}" >> $GITHUB_ENV
          echo "INPUT_START_TIME=${{ inputs.start_time }}" >> $GITHUB_ENV
          echo "INPUT_END_TIME=${{ env.END_TIME }}" >> $GITHUB_ENV
          echo "INPUT_CONTENT=${{ inputs.content }}" >> $GITHUB_ENV
          echo "INPUT_FAILURE=${{ inputs.failure }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the number's square
      id: get-square
      run: python ${{github.action_path}}/src/main.py
      shell: bash